name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.12.16
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: terraform ecr
        run: |
          ls
          export AWS_ACCESS_KEY_ID=AKIAYAYKC3LTOBRSCWKR
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_DEFAULT_REGION=us-east-1
          cd aws/modules/ecr
          terraform init
          terraform plan
      - name: ecr push pull demo
        run: |
          ls
          cd aws/modules/ecr
          ls
          export AWS_ACCESS_KEY_ID=AKIAYAYKC3LTOBRSCWKR
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_DEFAULT_REGION=us-east-1
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 551387585254.dkr.ecr.us-east-1.amazonaws.com
          docker tag archmydes:latest 551387585254.dkr.ecr.us-east-1.amazonaws.com/archmydes:latest
          docker build -t archmydes .
          docker tag archmydes:latest 551387585254.dkr.ecr.us-east-1.amazonaws.com/archmydes:latest
          docker push 551387585254.dkr.ecr.us-east-1.amazonaws.com/archmydes:latest
          docker images
          docker rmi 551387585254.dkr.ecr.us-east-1.amazonaws.com/archmydes:latest
          docker images
          docker pull 551387585254.dkr.ecr.us-east-1.amazonaws.com/archmydes:latest
          docker images
      - run: echo "🍏 This job's status is ${{ job.status }}."

